name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Get git short sha
      id: git_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT\
      
    - name: Build the Docker image
      run: docker build -t flaskapp:latest .

    - name: Test
      run: echo "TODO - Test"
    
    - name: Push to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 821594384510.dkr.ecr.us-east-1.amazonaws.com
        docker tag flaskapp:latest 821594384510.dkr.ecr.us-east-1.amazonaws.com/flaskapp:${{ steps.git_sha.outputs.sha_short }}
        docker tag flaskapp:latest 821594384510.dkr.ecr.us-east-1.amazonaws.com/flaskapp:latest
        docker push 821594384510.dkr.ecr.us-east-1.amazonaws.com/flaskapp:${{ steps.git_sha.outputs.sha_short }}
        docker push 821594384510.dkr.ecr.us-east-1.amazonaws.com/flaskapp:latest
